"""add_description_to_book

Revision ID: 87f92b009f70
Revises: 50aad3ab90a9
Create Date: 2025-05-19 23:18:11.541849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f92b009f70'
down_revision: Union[str, None] = '50aad3ab90a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book',
                  sa.Column('description', sa.String(length=500), nullable=False, server_default="тут будет описание"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'description')
    # ### end Alembic commands ###
